### ISSUE TITLE
Trusted Application API missing information 

### ISSUE THREAD

**Issue by mateusfreira** [OfficeDev/skype-docs#229]
I've followed the step by step  "Developing Trusted Application API applications for Skype for Business Online" available in [here](https://msdn.microsoft.com/en-us/skype/trusted-application-api/docs/developingapplicationsforsfbonline) and after all the auth steps completed, I've received an error when I try to access the 
https://api.skypeforbusiness.com/platformservice/discover
```
body: '{"code":"ServiceFailure","message":"Autodiscover failed!","debugInfo":{"errorReportId":"19351461356f4c5d80aa51f5df399935"}}' } '{"code":"ServiceFailure","message":"Autodiscover
failed!","debugInfo":{"errorReportId":"19351461356f4c5d80aa51f5df399935"}}
```

If I try to access any service other than the [discovery](https://api.skypeforbusiness.com/platformservice/discover),

For Example  https://ring2noammeetings.resources.lync.com/platformService/v1/applications
This other error is showed
```
{"code":"Forbidden","message":"Exception of type \\u0027PlatformService.Web.PlatformServiceWebException\\u0027 was thrown.","debugInfo":{"errorReportId":"9571a5e22cc64e0aa64ca42
a7c7806b7"}}' } '{"code":"Forbidden","message":"Exception of type \\u0027PlatformService.Web.PlatformServiceWebException\\u0027 was thrown.","debugInfo":{"errorReportId":"9571a5e22cc64e0
aa64ca42a7c7806b7"}}'
```

I know the Trusted Application API is new and maybe something is missing or incomplete about this step by step. I'm able to provide any information you need.

**Comment by victorltb** [comment]
👆 +1

**Comment by luizbaldi** [comment]
👍

**Comment by gustavohilario** [comment]
👍

**Comment by luizmacfilho** [comment]
+1

**Comment by jorgemarcondes** [comment]
+1

**Comment by arleyribeiro** [comment]
+1

**Comment by juarezhbr** [comment]
👏👍

**Comment by hugoalvares** [comment]
+1

**Comment by josemarcaetano** [comment]
+1

**Comment by FabioHOFernandes** [comment]
+1

**Comment by daianefreira** [comment]
+2

**Comment by billy-clay-myers** [comment]
@mateusfreira 

You have configured your app in Azure Active Directory and have completed registration for the app correct? Are you instantiating the ClientPlatform settings like this: _platformSettings = new ClientPlatformSettings(null, _aadClientId, null, _aadClientSecret, false);

This should then be followed by something similar to below.

` var platform = new ClientPlatform(_platformSettings, Logger);

            _eventChannel = new FakeEventChannel();
            var endpointSettings = new ApplicationEndpointSettings(_applicationEndpointId);
            _applicationEndpoint = new ApplicationEndpoint(platform, endpointSettings, _eventChannel);

            _applicationEndpoint.InitializeAsync(null).GetAwaiter().GetResult();
            _applicationEndpoint.InitializeApplicationAsync(null).GetAwaiter().GetResult();

            if (_applicationEndpoint.Application != null)
                _isInitialized = true;`

at the end of that, you should be able to call:
`var adhocMeeting = _applicationEndpoint.Application.CreateAdhocMeetingAsync(_loggingContext, adhocMeetingInput).Result;`

I have been working with this since the early early days before it became this nice SDK and so am happy to help if I can to get you up and going and maybe explain more of what is happening.

Are you running a fiddler trace to see what is going on in the transmit and return?

**Comment by felipeaniceto** [comment]
Nice

**Comment by mateusfreira** [comment]
@billy-clay-myers I'm not using the c# SDK, I'm building an integration in Node.js. After getting the access token I can't hit the discovery or any other endpoint listed in the documentation, I always get a "Forbidden" Or "Autodiscover failed!" as a result. Do you have an idea about how the SDK gets its keys? I'm now going to the to read the SDK code to understand what it does differently from the tutorial.

**Comment by tfischer** [comment]
For the applications request, I think you have to specify the application endpoint id as an argument to the request, like this:
   https://ring2noammeetings.resources.lync.com/platformService/v1/applications?endpointId=sip:yourRegisteredEndpoint@yourDomain.com

It seems to work that way in the sample code.

**Comment by bobchow123** [comment]
@mateusfreira I am using node.js too and had the similar situation. I added the endpointId in the application url(https://ring2noammeetings.resources.lync.com/platformService/v1/applications), but I still got the forbidden error. 
Had you solved the problem, would you mind to share your solution? Thanks

**Comment by bobchow123** [comment]
@mateusfreira I think maybe we had used an incorrect token, you may try the following program to obtain the token and test it again.
https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/dev/sample/client-credentials-sample.js
In my case, I got another error message after using the new token, maybe you can try it.

**Comment by humaruis** [comment]
@mateusfreira I'm also using node.js and encountered the same error, will appreciated it you can share the solution if it's solved.

**Comment by mateusfreira** [comment]
@humaruis I haven't solved it yet, I'll try the @bobchow123 suggestion, then let you know if it works.

**Comment by bobchow123** [comment]
@mateusfreira @humaruis I had successfully started the trusted application API with the token obtained from [adal](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/dev/sample/client-credentials-sample.js).

The _another error_ i mentioned in my pervious post is 'Failed to perform required BVD operation'. 
After I created a Trusted Application Endpoint and called 
/platformService/v1/applications?endpointId=sip:sample@xxx.com ,
I did not get the error anymore.

**Comment by kdilmurod** [comment]
@bobchow123 how you call /platformService/v1/applications?endpointId=sip:sample@xxx.com ?
 I created a Trusted Application Endpoint and when in browser called https://api.skypeforbusiness.com/platformService/v1/applications?endpointId=sip:kdilmurodtester@jazzsofter.onmicrosoft.com 
Goes error:
401 - Unauthorized: Access is denied due to invalid credentials.
You do not have permission to view this directory or page using the credentials that you supplied.

**Comment by humaruis** [comment]
@kdilmurod I just call the "https://api.skypeforbusiness.com/platformservice/discover" used the application context token, and we can extract "ms:rtc:saas:applications"(or "service:applications", not clear why it's changed from time to time) from the response. after that, i just called the applications endpoint which should be combined with endpointId(eg: https://ring2apacmeetings.resources.lync.com/platformService/v1/applications?endpointId=sip%3asample%40xxxxx.onmicrosoft.com) used the application token. it will return another application endpoint, used it you will retrieve all endpoints for each resources (resources for ad-hoc meeting, anonymous joining token, messaging, etc) .

**Comment by kdilmurod** [comment]
Hey.
We use the Postman.
We applied to the POST request at: https://login.windows.net/bf25176b-a9fd-42ae-bddf-331281ec4833/oauth2/token
With parameters
Client_id: xxxx-xxx-xxx
Client_secret: ZE4RHV7276ZKQ0vdp / n07m0YcMrfBw7QaPDxxxxxxbs =
Grant_type: client_credentials
Scope: https: //graph.microsoft.com/.default
And received a token
{
"Token_type": "Bearer",
"Expires_in": "3599",
"Ext_expires_in": "0",
"Expires_on": "1493804301",
"Not_before": "1493800401",
"Resource": "00000002-0000-0000-c000-000000000000"
"Access_token": "eyJ0 ..."
}

Next, we try to generate a GET request to https://api.skypeforbusiness.com/platformservice/discover
And got:
Ms: rtc: saas: applications ": {
"Href": "https://ring2noammeetings.resources.lync.com/platformService/v1/applications"
},
Next we try to compose a new text
Https://ring2noammeetings.resources.lync.com/platformService/v1/applications?endpointId=sip:skypeuser@natkz.onmicrosoft.com
We have an error 401 - Unauthorized: Access is denied due to invalid credentials.

When creating a POST request with the OAuth 2.0 authorization type and filling in the appropriate conditions for the above errors: Error obtaining an access token from the client credential flow. Could not send request.

How can we correctly determine the query? How to correctly add a token in a query?

**Comment by humaruis** [comment]
@kdilmurod do you add the 'Authorization': 'Bearer eyJ0 ...' to the headers when call the new endpoint (https://ring2noammeetings.resources.lync.com/platformService/v1/applications?endpointId=sip:skypeuser@natkz.onmicrosoft.com)?

eg:
request({
                method: 'GET',
                url: href + '?endpointId=sip:skypeuser@natkz.onmicrosoft.com',
                headers: { 'Authorization': 'Bearer eyJ0 ...' }
            }, function (error, response, body) {});

**Comment by kdilmurod** [comment]
@humaruis 
Did as you wrote. Received an error 403 - Forbidden: Access is denied.
Do I need to configure POSTMAN in addition - do I need to use a certificate to send a request?

**Comment by humaruis** [comment]
@kdilmurod I just follow this [blog](https://blogs.msdn.microsoft.com/tsmatsuz/2017/04/13/skype-for-business-trusted-application-api-tutorial/) and used nodejs to do it, i don't think you need to configure the POSTMAN and use a certificated to send that request since.

**Comment by kdilmurod** [comment]
@humaruis  Thank you, friend!
Finally it turned out for me, after one month research....  Thanks....

**Comment by medeirosrafael** [comment]
@kdilmurod what you did to work?

**Comment by kdilmurod** [comment]
@medeirosrafael Service for generate meeting urls.

**Comment by milacay** [comment]
@kdilmurod I am running in the the same problem. Please help explain how you did to work?  What is Service for generate meeting URLs?

**Comment by Linda-Editor** [comment]
@mateusfreira @victorltb @luizbaldi @gustavohilario @luizmacfilho @kdilmurod @milacay @medeirosrafael @humaruis Thanks for your feedback and collaboration on this topic. Please try the VBA developer community on Stack Overflow (https://stackoverflow.com/questions/tagged/skype) where you can get help from actual developers. If you find a bug in our documentation, please let us know. Thanks!
