### ISSUE TITLE
Tech Support guidance for Skype for Business

### ISSUE THREAD

**Issue by balkrishnabhave** [OfficeDev/skype-docs#63]
Technical Query:
"We are developing android and ios mobile apps. We want to develop voice and video communication functionality between any two app. It can be android to android and android to iOS. We are integrating with Skype for Business platform to utilize it's voice and video capability using Skype for business SDKs.

To achieve this, we need to generate a meeting instance and let two the users/apps join the meeting through SDK. Refer: https://msdn.microsoft.com/en-us/skype/appsdk/embedskypeb2ccomms. Hence, we are trying to get a meeting URL such as https://join.contoso.com/meet/john/BW9Z1MJD on-demand via our APIs (User API / UCWA). While trying to get the meeting URL on demand, it needs to authenticate the request again valid Skype for business user account.

Question: (1) Can we do this under our Skype for business online subscription? (2) There can be millions of user using our apps. Do we need to register all the users under Skype for Business subscription in order to enable them voice and video communication within our apps through Skype for Business (SFB) platform? (3) Can we impersonate the meeting url generation request by one or few SFB online user accounts, and let two mobile users (caller and attendee) join the meeting as annonymous users?"

When we tried to approach support they say as we are subscribed through GoDaddy, they cannot help us where as; as you see we need tech guidance on this? Can you please help or show direction?

**Comment by JohnAustin-MSFT** [comment]
These are good questions. We will provide guidance within a week.

**Comment by srividhc** [comment]
Going forward, please ask your questions on Stackoverflow with the tag: SkypeDeveloper

Question: (1) Can we do this under our Skype for business online subscription?
**Answer:** Yes

 (2) There can be millions of user using our apps. Do we need to register all the users under Skype for Business subscription in order to enable them voice and video communication within our apps through Skype for Business (SFB) platform?
**Answer:** The current scenario supported in the App SDK is the anonymous meeting join. Not authenticated meeting join scenario. The meeting should be created as an authenticated user. There is a limit to the number of anonymous users joining the meeting at a time. 

 (3) Can we impersonate the meeting url generation request by one or few SFB online user accounts, and let two mobile users (caller and attendee) join the meeting as annonymous users?"
**Answer:** Yes. this should be possible
