### ISSUE TITLE
Conversation control can't be used to open an incoming chat

### ISSUE THREAD

**Issue by ben-gilbert-smartsheet** [OfficeDev/skype-docs#79]
I'm trying to render the conversation control for an incoming chat, as described in the [renderConversation method docs](https://msdn.microsoft.com/en-us/skype/websdk/conversationcontrol).

I have a handle on the conversation object from the conversations.added event, and have successfully called conversation.chatService.accept().  However, when I try to call renderConversation, specifying { conversationId: conversation.id() }, I just get a blank conversation control with 0 participants.

Is this supposed to be working?  The guidance [here](https://msdn.microsoft.com/en-us/skype/websdk/useconversationcontrol#render-conversation-control-on-incoming-call) suggests that you can use the conversation control to render an incoming conversation, but the sample code uses participants to render the conversation, not a conversation ID.  Using participants works, but it seems to ignore the fact that I've specific a conversationId.

NOTE: the promise returned by renderConversation is being fulfilled successfully.  I've also attached a screenshot of the conversation control that results.

![image](https://cloud.githubusercontent.com/assets/5872106/17313270/fb9d9ed8-580e-11e6-8bfe-b8a2b06f9e91.png)

Thanks!
Ben Gilbert
Smartsheet.com

**Comment by sidharthv** [comment]
Hi Ben,

This looks like an error with the documentation. The `renderConversation` method that takes a `conversationId` parameter should be used to find existing multi party conversations with a `conversation.uri()` not `conversation.id()`. I'll get the documentation updated. 

For your scenario:
* if you are trying to render an existing p2p conversation then use the method that takes the participants array and provide just the sipuri of the remote party.
* If you are trying to render an existing multi party conversation then use the method with the conversationId parameter but pass in `conversation.uri()` instead. Don't use the participants array though, since that will create a new group conversation with those participants instead of fetching the existing one.

Let me know if you hit further issues.
Sidharth

**Comment by sidharthv** [comment]
Yep, `isGroupConversation()` can be used to determine which form of the `renderConversation` method to use.
