### ISSUE TITLE
is there any way to create group chat and open window to chat?

### ISSUE THREAD

**Issue by pravin-mindstix** [OfficeDev/skype-docs#84]
Hi,
"ms-sfb://chat?id=user@contoso.com" is only open's the window for individual user. But I want to create group for chat and open the window.

I have tried "ms-sfb://chat?id=user1@contoso.com;user2@contoso.com;"   but it's not working?

how can we do that using URI? like "ms-sfb://chat?id=user@contoso.com" ? 

Thanks,

**Comment by NT-D** [comment]
Hi, how about to try "'sip:example@example.com,sip:example2@example.com".
[This document](https://msdn.microsoft.com/skype/websdk/useconversationcontrol) describe the way to create group chat and open window with Skype Web SDK.

By the way, it is better to ask questions in [stackoverflow](http://stackoverflow.com/questions/tagged/skype). Because GitHub issue is for posting issue and stackoverflow is developers' community to ask and answer question. I think you will get answer faster in stackoverflow :)

thanks,
masa

**Comment by pravin-mindstix** [comment]
Thanks NT-D. 
Yeah sorry, actually my bad.  (This is not the issue of this repo).

**Comment by SadikWork** [comment]
@NT-D , I understand that this is not an issue with repo. I am just trying to do the same, trying to create and open a group conversation using ms-sfb URI. But not able to do so.

I asked this question everywhere- stackoverflow, microsft forum, github. But I dont have the solution yet.

here I saw you suggested something that worked for @pravin-mindstix .


I have tried:

1) ms-sfb://chat?id=sip:example@example.com, sip:example2@example.com

2) ms-sfb://chat?id=(example@example.com, example2@example.com)

didn't work.
I would be grateful If you guys can help me with exact syntax. :)
